#!/bin/bash
# для удобства отладки плагина

echo "Переустновка плагина в локальном docker"
cp ../target/releases/elasticsearch-position-similarity-8.4.1.zip ../docker/plugins
docker exec es8-dev  elasticsearch-plugin remove position-similarity
docker exec es8-dev   elasticsearch-plugin install file:///plugins/elasticsearch-position-similarity-8.4.1.zip
docker restart es8-dev
echo "Готово! Плагин переустановлен"
sleep 1


